# Output to InfluxDB
[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "mytoken123"
  organization = "mqtt-ass3"
  bucket = "mqtt_data"

# $SYS/# for broker stats
[[inputs.mqtt_consumer]]
  servers = ["tcp://broker:1883"]
  topics = ["$SYS/#"]
  client_id = "telegraf-01"
  data_format = "value"
  data_type = "string"

# counter/# to track message rates
[[inputs.mqtt_consumer]]
  servers = ["tcp://broker:1883"]
  topics = ["counter/#"]
  client_id = "telegraf-02"
  data_format = "value"
  data_type = "string"