apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    uid: influxdb-mqtt
    jsonData:
      version: Flux
      organization: mqtt-ass3
      defaultBucket: mqtt_data
      tlsSkipVerify: true
    secureJsonData:
      token: comp6310ass3
    editable: true